### ISSUE TITLE
Beat won't detect any files

### ISSUE THREAD

**Issue by rmarji** [GoogleCloudPlatform/gcsbeat#11]
I have tried local file approach and adding the bucket name. and it keeps saying files pending 0

it doesn't detect the files I wanted to be processed although I tried everything as a pattern from "*" to writing the file name exactly.

the file name is app.json and I have it in GCS in a bucket in a subfolder called android. what I'm doing wrong?

**Comment by josephlewis42** [comment]
Hi @rmarji would you mind including your beat configuration `.yml` file and any flags you're using to execute gcsbeat?

One thing that might be going on is `gcsbeat` will keep a database of already processed files and won't re-upload them so that database might be hanging around on your system.

Cheers!

**Comment by rmarji** [comment]
```
gcsbeat:
  interval: 1000s
  bucket_id: file:///home/<folder>/ or <bucket_name>
  json_key_file: key-test.json
  delete: false
  file_matches: "app.json"
  #file_exclude: "bak_*"
  #metadata_key: x-goog-meta-gcsbeat
  codec: "json-array"
  unpack_gzip: false
  processed_db_path: "processed_file_list.db"

```

that crossed my mind, and I deleted the db multiple times with the same result. I have never got any files download.
I replaced the values for the folder and bucketname. is there a format for the bucket name or jjust the name shown.
No Flags are used. it doesn't work on either the file system nor the bucket. and if I put a made up bucket name. it doesn't verify if that bucket actually exists so it was a bit confusing to check if I'm doing things correctly
